### ISSUE TITLE
The PN code should also accept an option for what time step to use.

### ISSUE THREAD

**Issue by vijayvarma392** [dongzesun/HybridizationWaveforms#11]
Right now, we can only ask for a certain number of steps per orbit.
https://github.com/dongzesun/HybridizationWaveforms/blob/9cbe6b1518c002936dc63447cb3c2973d325b991/PYPostNewtonian/Code/PostNewtonian.py#L26

In a lot of applications, we want to be able to specify a fixed time step.
While the user can interpolate the data, it is way more accurate to do this internally using dense output.
So, we want an option like dt, that defaults to None.
If dt is given, we use that, else steps per orbit.
If both are given, we raise an exception.

**Comment by vijayvarma392** [comment]
Similarly, it should ask for what ell_max to use, and only compute those modes. This can be set to ell_max=4 as default.

**Comment by dongzesun** [comment]
It's fixed.

**Comment by dongzesun** [comment]
It's fine if you pass StepsPerOrbit=64, it will not raise an error unless you pass it as well as dt.

**Comment by vijayvarma392** [comment]
Yeah, but it's weird code. 
You should do `if StepsPerOrbit != None`.

**Comment by vijayvarma392** [comment]
Or, do something like https://github.com/sxs-collaboration/gwsurrogate/blob/master/gwsurrogate/surrogate.py#L1988

**Comment by dongzesun** [comment]
Ok, it's fixed now.

**Comment by vijayvarma392** [comment]
Sorry, this is also bad :) https://github.com/dongzesun/HybridizationWaveforms/blob/9146bceed016d8e99f03ef6f5318c1e18acedffe/PYPostNewtonian/Code/PostNewtonian.py#L56

Now you are setting the default in the middle of the code, and someone that just sees the input arguments has no idea.
So, make the input argument default to StepsPerOrbit=32 by default as before.

And then check:
```
if not (StepsPerOrbit is None) ^ (dt is None):
    raise ValueError("Specify exactly one of StepsPerOrbit or dt.")  
````

This uses the xor operation.
Does this do what you want?
