### ISSUE TITLE
Compensate for angular velocity in cost function

### ISSUE THREAD

**Issue by moble** [dongzesun/HybridizationWaveforms#9]
While staring at this plot 

![image](https://user-images.githubusercontent.com/1470769/139484577-d8c2b2ce-f8d9-45a6-938f-6400e70d963e.png)

I realized that when trying to scale the problem, we were just making the units in the x and y directions equal, but we weren't doing anything about those long, thin valleys that cause trouble for the minimizer.  The reason they cause problems for the minimizer is that they're not long along any of the directions that we're scaling.  But we can easily change the cost function so that they *are* basically along a single direction.

We can define
```python
ω⃗0 = quaternion.quaternion(*np.mean(omega_NR[(W_NR.t>=t_start)&(W_NR.t<=t_end)]))
```
Then, we can compensate for the rotation due to time by adding in `ω⃗0*x[0]/2` to the rotation that's actually used in the cost function.  First, you correct the initial guess by changing
https://github.com/dongzesun/HybridizationWaveforms/blob/6de170db721d189828348cca25c6e38876280018/Hybridization.py#L108 to
```python
logR_delta = quaternion.as_float_array(np.log(R_delta) - ω⃗0*mint.x/2)
```
And then change this line in `Optimize4D` https://github.com/dongzesun/HybridizationWaveforms/blob/6de170db721d189828348cca25c6e38876280018/Hybridization.py#L115 to
```python
R_delta = np.exp(quaternion.quaternion(*x[1:4]) + ω⃗0*x[0]/2)
```
With that, we get something more like this:

![image](https://user-images.githubusercontent.com/1470769/139487034-0d8272cd-8577-4ed3-be53-7de338733096.png)

It may not be obvious, but those big blue bands really do go up as you move away from δt=0.
Now, if you use that as the cost function, and just pass `x_scale='jac'` to the minimizer, it'll basically look like a paraboloid near the minimum, which is exactly what the minimizer wants.  In fact, this is what I see closer to the minimum (just zooming in on the vertical scale) when compensating:

![image](https://user-images.githubusercontent.com/1470769/139700561-e1b831bb-423f-4291-8416-b8b4d39a4ae0.png)

You see it's very nicely circular, which is the goal.

**Comment by dongzesun** [comment]
Hi Mike, yes if the valley is straight we can certainly rescale along the valley, but for significant processing systems the valley doesn't has to be straight, except we do the alignment in coprocessing frame. Besides, for now the BFGS method can converge very fast even when handling valley shape cost functions, so is it necessary to rescale the cost function in coprocessing frame?

**Comment by moble** [comment]
Yeah, it would still be better to compensate for the angular velocity, because that will improve both robustness and speed.  

It will improve robustness by letting you set bounds more accurately.  Remember that you want the bounds to be small enough to make sure that the minimizer isn't jumping from one local minimum to another, but also large enough to be completely sure that the true minimum is within the bounds of the initial guess.  If you don't compensate for angular velocity, the bounds have to be relatively small, which means the initial guess has to be right, which may not be very reliable for all the different systems you're hoping to look at.

Judging from the first plot above, you'd have to get the initial guess within ~40M to ensure that the true minimum is within the bounds for the uncompensated cost function.  For the second and third (compensated) plots, you see that you have far more room.  In fact, it's more like 500M before you even get to another local minimum, but it's at a far higher cost.

It will also improve speed, because any time you have a valley, the minimizer has to spend extra iterations figuring out the shape of the valley, and taking smaller steps because any slight error in its estimate for the shape of the valley can lead to big errors in the cost.

> for significant processing systems the valley doesn't has to be straight, except we do the alignment in coprocessing frame

The example I showed above does actually have pretty significant precession, going through about half a precession cycle during the time over which the cost function is integrated.  And the comparison is in the inertial frame.  I expect this valley to be pretty straight for every system, even in the inertial frame.

Remember that the cost function integrates over a span of time, so just compensating with *the average* angular velocity over that span of time is all we need.  If the time offset is so large that *the average* angular velocity over the whole span of time changes by a lot, then you'll start to see the cost function look less like a paraboloid.  But you should be averaging over such a large span of time that this shouldn't be a problem.

So even for a precessing system like this, the compensated cost function just sees one nice, big, round minimum — which is exactly what we want.

> Besides, for now the BFGS method can converge very fast even when handling valley shape cost functions

It will still typically be slower and less accurate if you don't compensate.  As a general rule, if you can make a problem easier, you should.
